# Generated by Django 4.2.30 on 2026-09-08 00:06

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('key', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=80)),
                ('mode', models.CharField(choices=[('featured', 'Featured'), ('cat', 'Category')], max_length=20)),
                ('cat', models.CharField(blank=True, default='', max_length=20)),
                ('on', models.BooleanField(default=True)),
                ('position', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cost', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('casual', 'Casual'), ('fiesta', 'Fiesta'), ('accesorios', 'Accesorios')], max_length=20)),
                ('sizes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('Único', 'Único')], max_length=10), size=None)),
                ('colors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Negro', 'Negro'), ('Blanco', 'Blanco'), ('Rosa', 'Rosa'), ('Fucsia', 'Fucsia'), ('Rojo', 'Rojo'), ('Beige', 'Beige'), ('Celeste', 'Celeste'), ('Dorado', 'Dorado')], max_length=20), size=None)),
                ('featured', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('whatsapp', models.CharField(default='', max_length=20)),
                ('margin', models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(90)])),
                ('pin_hash', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hero_title', models.CharField(default='Ropa que te hace sentir linda', max_length=255)),
                ('hero_sub', models.TextField(default='Elegís, nos escribís por WhatsApp y te lo llevamos. Así de simple, bonita.')),
                ('ship_title', models.CharField(default='Envíos y pagos', max_length=255)),
                ('ship_sub', models.CharField(default='Entrega en Apóstoles y alrededores', max_length=255)),
                ('closing', models.CharField(default='gracias por estar acá', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Site Content',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=120)),
                ('unit_price', models.PositiveIntegerField()),
                ('qty', models.PositiveSmallIntegerField(default=1)),
                ('date', models.DateField()),
                ('profit', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='api.product')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='products/')),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.product')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
