# Generated by Django 4.2.30 on 2026-09-08 00:21

from django.db import migrations
from django.contrib.auth.hashers import make_password


def seed_data(apps, schema_editor):
    HomeSection = apps.get_model('api', 'HomeSection')
    SiteContent = apps.get_model('api', 'SiteContent')
    Settings = apps.get_model('api', 'Settings')

    # Create HomeSections
    sections = [
        {'key': 'nov', 'title': 'Recién llegado', 'mode': 'featured', 'cat': '', 'on': True, 'position': 0},
        {'key': 'cas', 'title': 'Para todos los días', 'mode': 'cat', 'cat': 'casual', 'on': True, 'position': 1},
        {'key': 'fie', 'title': 'Noches de fiesta', 'mode': 'cat', 'cat': 'fiesta', 'on': True, 'position': 2},
        {'key': 'acc', 'title': 'Detalles que suman', 'mode': 'cat', 'cat': 'accesorios', 'on': True, 'position': 3},
    ]

    for section in sections:
        HomeSection.objects.get_or_create(key=section['key'], defaults=section)

    # Create SiteContent
    SiteContent.objects.get_or_create(id=1, defaults={
        'hero_title': 'Ropa que te hace sentir linda',
        'hero_sub': 'Elegís, nos escribís por WhatsApp y te lo llevamos. Así de simple, bonita.',
        'ship_title': 'Envíos y pagos',
        'ship_sub': 'Entrega en Apóstoles y alrededores',
        'closing': 'gracias por estar acá',
    })

    # Create Settings with default PIN
    Settings.objects.get_or_create(id=1, defaults={
        'whatsapp': '',
        'margin': 60,
        'pin_hash': make_password('lunarosa'),
    })


def reverse_seed(apps, schema_editor):
    HomeSection = apps.get_model('api', 'HomeSection')
    SiteContent = apps.get_model('api', 'SiteContent')
    Settings = apps.get_model('api', 'Settings')

    HomeSection.objects.all().delete()
    SiteContent.objects.filter(id=1).delete()
    Settings.objects.filter(id=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_data, reverse_seed),
    ]
