# Generated by Django 4.2.30 on 2026-09-08 00:21

from django.db import migrations
import uuid


def seed_products(apps, schema_editor):
    Product = apps.get_model('api', 'Product')

    products = [
        {
            'id': uuid.uuid4(),
            'name': 'Vestido Selene',
            'price': 38000,
            'cost': 0,
            'category': 'fiesta',
            'sizes': ['S', 'M', 'L'],
            'colors': ['Negro', 'Rojo'],
            'featured': True,
            'active': True,
            'position': 0,
        },
        {
            'id': uuid.uuid4(),
            'name': 'Blusa Aurora',
            'price': 19500,
            'cost': 0,
            'category': 'casual',
            'sizes': ['S', 'M', 'L'],
            'colors': ['Blanco', 'Rosa'],
            'featured': True,
            'active': True,
            'position': 1,
        },
        {
            'id': uuid.uuid4(),
            'name': 'Jean Luna',
            'price': 27000,
            'cost': 0,
            'category': 'casual',
            'sizes': ['XS', 'S', 'M', 'L'],
            'colors': ['Celeste'],
            'featured': False,
            'active': True,
            'position': 2,
        },
        {
            'id': uuid.uuid4(),
            'name': 'Top Estrella',
            'price': 15000,
            'cost': 0,
            'category': 'fiesta',
            'sizes': ['S', 'M'],
            'colors': ['Negro', 'Dorado'],
            'featured': True,
            'active': True,
            'position': 3,
        },
        {
            'id': uuid.uuid4(),
            'name': 'Aros Media Luna',
            'price': 8900,
            'cost': 0,
            'category': 'accesorios',
            'sizes': ['Único'],
            'colors': ['Dorado'],
            'featured': False,
            'active': True,
            'position': 4,
        },
        {
            'id': uuid.uuid4(),
            'name': 'Falda Petal',
            'price': 21000,
            'cost': 0,
            'category': 'casual',
            'sizes': ['XS', 'S', 'M'],
            'colors': ['Rosa', 'Negro'],
            'featured': False,
            'active': True,
            'position': 5,
        },
    ]

    for product in products:
        Product.objects.get_or_create(id=product['id'], defaults=product)


def reverse_products(apps, schema_editor):
    Product = apps.get_model('api', 'Product')
    Product.objects.filter(name__in=[
        'Vestido Selene', 'Blusa Aurora', 'Jean Luna', 'Top Estrella',
        'Aros Media Luna', 'Falda Petal'
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_seed_home_sections'),
    ]

    operations = [
        migrations.RunPython(seed_products, reverse_products),
    ]
