# Generated by Django 4.2.30 on 2026-09-08 01:49

from django.db import migrations, models

# El front consume las categorias capitalizadas (types.ts: Category).
MAPA = {'casual': 'Casual', 'fiesta': 'Fiesta', 'accesorios': 'Accesorios'}


def capitalizar(apps, schema_editor):
    Product = apps.get_model('api', 'Product')
    HomeSection = apps.get_model('api', 'HomeSection')
    for viejo, nuevo in MAPA.items():
        Product.objects.filter(category=viejo).update(category=nuevo)
        HomeSection.objects.filter(cat=viejo).update(cat=nuevo)


def revertir(apps, schema_editor):
    Product = apps.get_model('api', 'Product')
    HomeSection = apps.get_model('api', 'HomeSection')
    for viejo, nuevo in MAPA.items():
        Product.objects.filter(category=nuevo).update(category=viejo)
        HomeSection.objects.filter(cat=nuevo).update(cat=viejo)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_seed_sample_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Casual', 'Casual'), ('Fiesta', 'Fiesta'), ('Accesorios', 'Accesorios')], max_length=20),
        ),
        migrations.RunPython(capitalizar, revertir),
    ]
