# Generated by Django 4.2.30 on 2026-09-08 03:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('supplier', models.CharField(blank=True, default='', max_length=120)),
                ('shipping_cost', models.PositiveIntegerField(default=0)),
                ('margin', models.PositiveSmallIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('photo', models.URLField(blank=True, default='', max_length=500)),
                ('unit_cost', models.PositiveIntegerField()),
                ('qty', models.PositiveSmallIntegerField(default=1)),
                ('margin', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('position', models.IntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.purchaseorder')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
