"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-ryj2^$_%=oz^@ot$)t9!mgm3jwe-8b#)5s_vtc8lkgry_hz_9o')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='',
    cast=lambda v: [s.strip() for s in v.split(',') if s.strip()],
)
# El healthcheck del container pega a localhost; sin esto Django responde 400
# y el orquestador reinicia el container en loop.
ALLOWED_HOSTS += ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'storages',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='lunarosa'),
        'USER': config('DB_USER', default='postgres'),
        'PASSWORD': config('DB_PASSWORD', default='postgres'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Whitenoise sirve /static/ cuando DEBUG=False (el admin de Django lo necesita).
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

# Valores por defecto (disco local). El bloque USE_S3 de abajo los pisa
# cuando el almacenamiento va a R2, asi que tienen que quedar ANTES.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ---------------------------------------------------------------------------
# Almacenamiento de fotos: disco local, o S3 / Cloudflare R2 con USE_S3=True.
#
# En un contenedor el disco es efimero: cada redeploy borra las fotos. Para
# produccion va R2, o un volumen persistente montado en MEDIA_ROOT.
# ---------------------------------------------------------------------------
USE_S3 = config('USE_S3', default=False, cast=bool)

if USE_S3:
    STORAGES['default'] = {'BACKEND': 'storages.backends.s3.S3Storage'}

    AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='auto')
    AWS_S3_ENDPOINT_URL = config('AWS_S3_ENDPOINT_URL', default='')

    # R2 NO implementa ACLs. Si django-storages manda 'public-read' la subida
    # falla; con None no se envia el header.
    AWS_DEFAULT_ACL = None
    AWS_S3_SIGNATURE_VERSION = 's3v4'

    # URLs limpias y estables en vez de links firmados que expiran.
    AWS_QUERYSTRING_AUTH = False

    # Sin sobrescribir: cada subida recibe un nombre unico. Si se reutilizara
    # el nombre, la CDN seguiria sirviendo la foto vieja desde su cache.
    AWS_S3_FILE_OVERWRITE = False
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=31536000, immutable'}

    # El bucket de R2 no es publico por su endpoint S3: hace falta el
    # subdominio r2.dev o un dominio propio para que el navegador vea las
    # fotos. Sin esto las URLs apuntan al endpoint S3 y dan 401.
    AWS_S3_CUSTOM_DOMAIN = config('AWS_S3_CUSTOM_DOMAIN', default='')
    if AWS_S3_CUSTOM_DOMAIN:
        MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'

    # ------------------------------------------------------------------
    # Falla el arranque en vez de servir URLs de fotos rotas en silencio.
    #
    # Sin AWS_S3_CUSTOM_DOMAIN, S3Storage.url() SIEMPRE genera un presigned
    # url contra el endpoint privado (*.r2.cloudflarestorage.com): ese
    # endpoint exige firma y el navegador recibe 400 al intentar abrirlo, y
    # el visitante ve el cuadrado vacio. No es un caso raro: es el
    # comportamiento por default de django-storages cuando falta esta
    # variable, asi que se detecta acá antes que en el bug report.
    # ------------------------------------------------------------------
    if not AWS_S3_CUSTOM_DOMAIN:
        raise ImproperlyConfigured(
            'USE_S3=True pero falta AWS_S3_CUSTOM_DOMAIN. Sin esa variable, '
            'las fotos quedan con URLs del endpoint privado de R2 '
            '(*.r2.cloudflarestorage.com), que el navegador no puede abrir '
            '(400/401): se ven como un cuadrado vacio. '
            'Activa "Public Access" en el bucket de R2 (subdominio r2.dev, '
            'o un dominio propio) y poné ese host en AWS_S3_CUSTOM_DOMAIN.'
        )

    # El nombre de bucket no puede llevar "/": bucket y ruta son campos
    # distintos (AWS_STORAGE_BUCKET_NAME vs. la carpeta va en AWS_LOCATION).
    # Confundirlos produce URLs con un segmento duplicado como
    # ".../tienda/tienda/products/foto.jpg".
    if '/' in AWS_STORAGE_BUCKET_NAME:
        raise ImproperlyConfigured(
            f"AWS_STORAGE_BUCKET_NAME={AWS_STORAGE_BUCKET_NAME!r} no puede "
            "contener '/'. Es solo el nombre del bucket en R2. Si buscás "
            "namespacing por carpeta, usá AWS_LOCATION para el prefijo."
        )

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # Bearer primero: es el esquema que manda el front. TokenAuthentication
        # queda como fallback para clientes que usen 'Token <key>'.
        'api.authentication.BearerTokenAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    # camelCase en toda la API para que el front no traduzca.
    # OJO con el nombre del modulo: es 'djangorestframework_camel_case',
    # no 'rest_framework_camel_case'.
    'DEFAULT_RENDERER_CLASSES': [
        # JSON PRIMERO: DRF usa el primero como default. Si va el Browsable
        # arriba, el front recibe HTML en vez de JSON.
        'djangorestframework_camel_case.render.CamelCaseJSONRenderer',
        'djangorestframework_camel_case.render.CamelCaseBrowsableAPIRenderer',
    ],
    # Los parsers hacen el camino inverso: el front manda unitPrice y los
    # serializers reciben unit_price.
    'DEFAULT_PARSER_CLASSES': [
        'djangorestframework_camel_case.parser.CamelCaseJSONParser',
        'djangorestframework_camel_case.parser.CamelCaseMultiPartParser',
        'djangorestframework_camel_case.parser.CamelCaseFormParser',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
        # Login: limita fuerza bruta sobre email/password por IP.
        'login': config('LOGIN_THROTTLE_RATE', default='5/min'),
    },
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:5173,http://localhost:3000',
    cast=lambda v: [s.strip() for s in v.split(',')]
)

# File Upload
DATA_UPLOAD_MAX_MEMORY_SIZE = 8 * 1024 * 1024  # 8MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 8 * 1024 * 1024  # 8MB
